##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES
#
# url is your site domain. For GitHub Pages, it is your username.github.io
url: "https://juanbardina.github.io"
# baseurl is the path to your repository. It must match your repo name exactly.
baseurl: "/Familia"
# location of code
source-code: https://github.com/juanbardina/Familia

##########
# SITE SETTINGS
#
# title of site appears in banner
title: "Juan Bardina fotos"
# tagline appears throughout the site in the top banner
tagline: "Family History Archive"
# description appears in meta tags for search results
description: "un archivo digital de fotos del celular de Juan Bardina"
# creator of the digital collection
author: "Juan Bardina"

##########
# COLLECTION SETTINGS
#
# Point to your CSV file in the _data directory (without the .csv extension)
metadata: metadata

##########
# BUILD SETTINGS 
#
# This section tells Jekyll which files to ignore to prevent build errors.
# We include 'vendor' and 'docs' to stop the "Invalid Date" exit code 1 error.
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, vendor, Gemfile, Gemfile.lock, .github]

# compress CSS output
sass:
  style: compressed
